# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a100tcsg324-3
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /afs/athena.mit.edu/user/b/t/btushig/Desktop/6.111/Final_Project/Final_Project.cache/wt [current_project]
set_property parent.project_path /afs/athena.mit.edu/user/b/t/btushig/Desktop/6.111/Final_Project/Final_Project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_ip /afs/athena.mit.edu/user/b/t/btushig/Desktop/6.111/Final_Project/Final_Project.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all /afs/athena.mit.edu/user/b/t/btushig/Desktop/6.111/Final_Project/Final_Project.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/athena.mit.edu/user/b/t/btushig/Desktop/6.111/Final_Project/Final_Project.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.dcp]
set_property is_locked true [get_files /afs/athena.mit.edu/user/b/t/btushig/Desktop/6.111/Final_Project/Final_Project.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci]

read_verilog -library xil_defaultlib {
  /afs/athena.mit.edu/user/b/t/btushig/Desktop/6.111/Final_Project/Final_Project.srcs/sources_1/imports/sources_1/imports/src/SCCB_interface.v
  /afs/athena.mit.edu/user/b/t/btushig/Desktop/6.111/Final_Project/Final_Project.srcs/sources_1/imports/sources_1/imports/src/OV7670_config_rom.v
  /afs/athena.mit.edu/user/b/t/btushig/Desktop/6.111/Final_Project/Final_Project.srcs/sources_1/imports/sources_1/imports/src/OV7670_config.v
  /afs/athena.mit.edu/user/b/t/btushig/Desktop/6.111/Final_Project/Final_Project.srcs/sources_1/imports/sources_1/imports/src/camera_read.v
  /afs/athena.mit.edu/user/b/t/btushig/Desktop/6.111/Final_Project/Final_Project.srcs/sources_1/imports/sources_1/imports/src/camera_configure.v
  /afs/athena.mit.edu/user/b/t/btushig/Desktop/6.111/Final_Project/Final_Project.srcs/sources_1/imports/sources_1/new/main.v
}
read_xdc /afs/athena.mit.edu/user/b/t/btushig/Desktop/6.111/Final_Project/Final_Project.srcs/constrs_1/imports/Sources/Nexys4DDR_Master_lab4.xdc
set_property used_in_implementation false [get_files /afs/athena.mit.edu/user/b/t/btushig/Desktop/6.111/Final_Project/Final_Project.srcs/constrs_1/imports/Sources/Nexys4DDR_Master_lab4.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
catch { write_hwdef -file main.hwdef }
synth_design -top main -part xc7a100tcsg324-3
write_checkpoint -noxdef main.dcp
catch { report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb }
